const C = window.MINGPIAN_CONFIG || {};
const app = document.querySelector('#app');
const toast = document.querySelector('#toast');
const state = { page:'home', cards:[], query:'', image:null, token:null, editing:null };
const icon = { plus:'＋', back:'‹', search:'⌕', share:'↗', camera:'◉', map:'⌖', phone:'☎', mail:'✉', web:'◎' };

function escape(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function now(){return new Date().toLocaleString('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).replaceAll('-','/')}
function notice(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)}
function cardArt(card){return `<div class="card-art" style="background:${escape(card.color||'#7b9f87')}"><span>${escape((card.company||'名片').slice(0,2))}</span></div>`}
function nav(page,id){state.page=page;if(id) state.editing=state.cards.find(x=>x.id===id);render()}

function render(){
  if(state.page==='home') app.innerHTML=home();
  if(state.page==='wallet') app.innerHTML=wallet();
  if(state.page==='add') app.innerHTML=add();
  if(state.page==='editor') app.innerHTML=editor();
  if(state.page==='detail') app.innerHTML=detail();
  bind();
}
function home(){return `<section class="screen"><div class="top"><b class="logo">名</b><button class="round" data-action="settings">⚙</button></div><div class="welcome"><p>您好</p><h1>把每一次相遇，<br><em>好好收藏。</em></h1><span>拍下一張名片，讓人脈更容易被記住。</span></div><button class="quick" data-action="add"><i>${icon.camera}</i><span><b>新增一張名片</b><small>拍照或從相簿選取</small></span><strong>›</strong></button><button class="wallet" data-action="wallet"><i class="mini">▤</i><span><b>我的名片夾</b><small>已收藏 ${state.cards.length} 位人脈</small></span><strong>›</strong></button><p class="privacy">✦ 資料只會存入您授權的 Google Drive</p></section>`}
function header(title,right=''){return `<header><button data-action="back">${icon.back}</button><h2>${title}</h2><span>${right}</span></header>`}
function wallet(){const q=state.query.toLowerCase();const cards=state.cards.filter(c=>`${c.name} ${c.company} ${c.tags}`.toLowerCase().includes(q));return `<section class="screen">${header('我的名片夾',`<button class="add-circle" data-action="add">${icon.plus}</button>`)}<label class="search">${icon.search}<input id="search" placeholder="搜尋姓名、公司或標籤" value="${escape(state.query)}">${state.query?'<button data-action="clear-search">×</button>':''}</label><p class="count">共 ${cards.length} 位人脈</p><div class="list">${cards.map(c=>`<button class="contact" data-action="detail" data-id="${c.id}">${cardArt(c)}<span><b>${escape(c.name||'未命名')}</b><small>${escape(c.company||'未填公司')}</small><em>${escape(c.tags||'未分類')}</em></span><strong>›</strong></button>`).join('')||'<div class="empty">⌕<b>尚未找到相符的人脈</b><span>試試姓名、公司或備註標籤。</span></div>'}</div></section>`}
function add(){return `<section class="screen">${header('智慧新增')}<div class="seg"><button class="on">單面名片</button><button>雙面名片</button></div><label class="drop" id="drop"><input id="photo" type="file" accept="image/*" capture="environment"><span>${icon.camera}</span><b>拍照或從相簿選取</b><small>支援 JPG、PNG；雙面名片可依序加入兩張</small></label><div class="tip"><i>✦</i><p><b>拍得清楚，辨識更準確</b><span>請盡量讓名片平放、文字清晰且避免反光。</span></p></div></section>`}
function editor(){const c=state.editing||{};const img=state.image?`<img src="${state.image}" alt="名片預覽">`:'<div class="fake-card">Business<br>Card</div>';return `<section class="screen editor">${header('核對名片資料')}<div class="preview">${img}</div><p class="hint">暖橘色欄位表示辨識信心較低，請優先確認。</p><form id="card-form"><input type="hidden" name="id" value="${escape(c.id||'')}"><label>姓名<input name="name" value="${escape(c.name||'') }" placeholder="請輸入姓名"></label><label>公司名稱<input name="company" value="${escape(c.company||'')}" placeholder="請輸入公司名稱"></label><label>統一編號（選填）<input name="taxId" value="${escape(c.taxId||'')}" placeholder="8 碼統一編號"></label><label>職稱<input name="title" value="${escape(c.title||'')}" placeholder="請輸入職稱"></label><label class="low">手機號碼<input name="mobile" value="${escape(c.mobile||'')}" placeholder="例如 0912-345-678"></label><label>公司電話<input name="phone" value="${escape(c.phone||'')}" placeholder="含分機"></label><label>電子郵件<input name="email" value="${escape(c.email||'')}" placeholder="name@example.com"></label><label>公司地址<input name="address" value="${escape(c.address||'')}" placeholder="可填入多個地址"></label><label>官方網站／社群<input name="website" value="${escape(c.website||'')}" placeholder="網址、FB、LinkedIn"></label><label>通訊軟體 ID<input name="messaging" value="${escape(c.messaging||'')}" placeholder="LINE、WeChat、WhatsApp"></label><label>備註／標籤<textarea name="tags" placeholder="例如：BNI 大展分會、防水、僑外資">${escape(c.tags||'')}</textarea></label><button class="save" type="submit">保存至名片夾</button></form></section>`}
function detail(){const c=state.editing; if(!c)return home();const rows=[['☎','手機號碼',c.mobile],['☎','公司電話',c.phone],['✉','電子郵件',c.email],['⌖','公司地址',c.address],['◎','官方網站',c.website]];return `<section class="screen">${header('名片詳情',`<button data-action="share">${icon.share}</button>`)}<div class="detail-card">${c.image?`<img src="${c.image}" alt="名片">`:cardArt(c)}<div><small>${escape(c.company||'未填公司')}</small><h1>${escape(c.name||'未命名')}</h1><p>${escape(c.title||'')}</p></div></div><div class="details">${rows.filter(x=>x[2]).map(r=>`<div><i>${r[0]}</i><span><small>${r[1]}</small><b>${escape(r[2])}</b></span>${r[1]==='公司地址'?'<button data-action="map">導航</button>':''}</div>`).join('')}</div><div class="tags"><small>備註／標籤</small><p>${escape(c.tags||'未設定')}</p><em>首次建立：${escape(c.createdAt||'')}</em></div><footer><button data-action="edit">編輯</button><button class="save" data-action="share">分享與轉介紹</button></footer></section>`}

function parseOCR(text){const lines=text.replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(Boolean);const take=re=>lines.find(x=>re.test(x))||'';const email=take(/[\w.+-]+@[\w-]+\.[\w.-]+/);const mobile=take(/(?:\+886|0)9\d{2}[\s-]?\d{3}[\s-]?\d{3}/);const phone=take(/(?:0\d{1,3}[-\s]?)?\d{3,4}[-\s]?\d{3,4}(?:\s*(?:#|分機|ext\.?)[\s\d]+)?/);const website=take(/(?:https?:\/\/|www\.)\S+/i);const address=take(/(?:台|新|桃|臺|高|台中|台南|基隆|宜蘭|花蓮|屏東|嘉義|彰化|苗栗|雲林|南投)[^\n]{4,}(?:路|街|區|市|縣)/);return {name:lines[0]||'',company:lines[1]||'',title:lines[2]||'',mobile,phone,email,website,address,tags:''}}
async function doOCR(){if(!state.image){nav('editor');return}notice('正在辨識名片…');const base64=state.image.split(',')[1]||await urlToBase64(state.image);let r,j;if(C.ocrWorkerUrl){r=await fetch(C.ocrWorkerUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({image:base64})});j=await r.json();if(!r.ok)throw new Error(j.error||'OCR 辨識失敗')}else if(C.ocrSpaceApiKey){const form=new FormData();form.set('base64Image',`data:image/jpeg;base64,${base64}`);form.set('language','cht');form.set('isOverlayRequired','true');form.set('detectOrientation','true');form.set('scale','true');r=await fetch('https://api.ocr.space/parse/image',{method:'POST',headers:{apikey:C.ocrSpaceApiKey},body:form});j=await r.json();if(!r.ok||j.IsErroredOnProcessing)throw new Error(j.ErrorMessage?.join('；')||'OCR.Space 辨識失敗');j={text:j.ParsedResults?.map(x=>x.ParsedText).join('\n')||''}}else{state.editing={...parseOCR(''),image:state.image};notice('尚未設定 OCR.Space Key，請先手動核對欄位');nav('editor');return}state.editing={...parseOCR(j.text||''),image:state.image};nav('editor')}
function urlToBase64(url){return fetch(url).then(r=>r.blob()).then(b=>new Promise(ok=>{const f=new FileReader();f.onload=()=>ok(f.result.split(',')[1]);f.readAsDataURL(b)}))}
function bind(){document.querySelectorAll('[data-action]').forEach(el=>el.onclick=async()=>{const a=el.dataset.action;try{if(a==='home'||a==='back')nav(state.page==='detail'?'wallet':'home');if(a==='add')nav('add');if(a==='wallet')nav('wallet');if(a==='detail')nav('detail',Number(el.dataset.id));if(a==='clear-search'){state.query='';render()}if(a==='edit')nav('editor');if(a==='share')shareCard();if(a==='map')window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(state.editing.address||''),'_blank');if(a==='settings')connectDrive()}catch(e){notice(e.message||'操作未完成')}});const search=document.querySelector('#search');if(search)search.oninput=e=>{state.query=e.target.value;render()};const photo=document.querySelector('#photo');if(photo)photo.onchange=async e=>{const f=e.target.files[0];if(!f)return;state.image=await fileData(f);try{await doOCR()}catch(err){notice(err.message);state.editing={...parseOCR(''),image:state.image};nav('editor')}};const form=document.querySelector('#card-form');if(form)form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));const card={...state.editing,...data,id:data.id?Number(data.id):Date.now(),createdAt:state.editing?.createdAt||now(),updatedAt:now(),image:state.image||state.editing?.image||'',color:'#7b9f87'};const ix=state.cards.findIndex(x=>x.id===card.id);if(ix>=0)state.cards[ix]=card;else state.cards.unshift(card);state.editing=card;await saveCards();notice('成功保留了一段新的人脈');nav('detail')}}
function fileData(file){return new Promise(ok=>{const r=new FileReader();r.onload=()=>ok(r.result);r.readAsDataURL(file)})}
function shareCard(){const c=state.editing;const text=`這是我推薦的人脈：${c.name||''}｜${c.company||''}\n${c.title||''}\n電話：${c.mobile||c.phone||''}\n${c.email||''}`;navigator.share?navigator.share({title:`${c.name} 的名片`,text}):navigator.clipboard.writeText(text).then(()=>notice('分享文字已複製，可貼到 LINE 或微信'))}
async function connectDrive(){if(!C.googleClientId){notice('請先在 config.js 填入 Google OAuth Client ID');return}if(!window.google?.accounts?.oauth2){notice('Google 登入服務正在載入，請稍後再試');return}window.google.accounts.oauth2.initTokenClient({client_id:C.googleClientId,scope:'https://www.googleapis.com/auth/drive.appdata',callback:async r=>{state.token=r.access_token;await loadCards();notice('已連結您的 Google Drive');render()}}).requestAccessToken()}
async function loadCards(){if(!state.token)return;const h={Authorization:'Bearer '+state.token};const q=encodeURIComponent("name='mingpianbao-data.json' and 'appDataFolder' in parents and trashed=false");const list=await fetch('https://www.googleapis.com/drive/v3/files?q='+q+'&spaces=appDataFolder&fields=files(id)',{headers:h}).then(r=>r.json());if(list.files?.[0])state.cards=await fetch('https://www.googleapis.com/drive/v3/files/'+list.files[0].id+'?alt=media',{headers:h}).then(r=>r.json())}
async function saveCards(){if(!state.token){notice('已暫存於目前畫面；連結 Google Drive 後才會雲端保存');return}const h={Authorization:'Bearer '+state.token,'Content-Type':'application/json'};const q=encodeURIComponent("name='mingpianbao-data.json' and 'appDataFolder' in parents and trashed=false");const list=await fetch('https://www.googleapis.com/drive/v3/files?q='+q+'&spaces=appDataFolder&fields=files(id)',{headers:h}).then(r=>r.json());const body=JSON.stringify(state.cards);let id=list.files?.[0]?.id;if(!id){const file=await fetch('https://www.googleapis.com/drive/v3/files',{method:'POST',headers:h,body:JSON.stringify({name:'mingpianbao-data.json',parents:['appDataFolder'],mimeType:'application/json'})}).then(r=>r.json());id=file.id}const saved=await fetch('https://www.googleapis.com/upload/drive/v3/files/'+id+'?uploadType=media',{method:'PATCH',headers:h,body});if(!saved.ok)throw new Error('Google Drive 儲存失敗')}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
